use_frameworks!
##忽略.cocoapods中多个specs源引起的警告问题
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
platform :ios, '10.0'

target 'ZHHUnicodeReadable_Example' do
  pod 'ZHHUnicodeReadable', :path => '../'

  target 'ZHHUnicodeReadable_Tests' do
    inherit! :search_paths

    
  end
end
